/**
 * TypeScript interfaces derived from backend Pydantic models.
 * These types ensure type safety across the frontend application.
 */

// Status severity levels
export type Severity = 'green' | 'yellow' | 'red';

// Alert urgency levels
export type AlertLevel = 'info' | 'warning' | 'critical';

// Object detection result from DeepStream
export interface Detection {
  class_id: number;
  class_name: string;
  confidence: number;
  bbox: [number, number, number, number]; // [x1, y1, x2, y2]
}

// Detection event from DeepStream container
export interface DetectionEvent {
  type: 'detection.received';
  stream_id: string;
  frame_path?: string;
  detections: Detection[];
  timestamp: number;
}

// Current status for a monitored stream
export interface StreamStatus {
  stream_id: string;
  severity: Severity;
  icon: string;
  description: string;
  confidence: number;
  timestamp: string;
}

// VLM summary event
export interface SummaryEvent {
  type: 'summary.received';
  stream_id: string;
  data: Record<string, unknown>;
  timestamp: number;
}

// Alert generated by the system
export interface Alert {
  id: string;
  stream_id: string;
  level: AlertLevel;
  title: string;
  message: string;
  severity: Severity;
  timestamp: string;
  acknowledged: boolean;
  resolved_at?: string;
}

// User-defined monitoring protocol rules
export interface ProtocolRules {
  green_rules: string;
  yellow_rules: string;
  red_rules: string;
}

// Configuration for a monitored stream
export interface StreamConfig {
  stream_id: string;
  name: string;
  source_uri: string;
  enabled: boolean;
  protocols?: ProtocolRules;
}

// Full application configuration
export interface AppConfig {
  feeds: StreamConfig[];
  protocols: ProtocolRules;
  created_at?: string;
  updated_at?: string;
}

// WebSocket message types
export type WSMessageType =
  | 'status_update'
  | 'alert_new'
  | 'detection'
  | 'query'
  | 'query_response'
  | 'query_received'
  | 'ping'
  | 'pong';

// WebSocket status update message
export interface WSStatusUpdate {
  type: 'status_update';
  stream_id: string;
  severity: Severity;
  icon: string;
  description: string;
  timestamp: string;
}

// WebSocket alert message
export interface WSAlert {
  type: 'alert_new';
  alert: Alert;
}

// WebSocket detection message
export interface WSDetection {
  type: 'detection';
  stream_id: string;
  detections: Detection[];
  timestamp: string;
}

// WebSocket query from client
export interface WSQuery {
  type: 'query';
  stream_id: string;
  question: string;
  request_id?: string;
}

// WebSocket query response
export interface WSQueryResponse {
  type: 'query_response';
  request_id?: string;
  answer: string;
  timestamp: string;
}

// WebSocket query received acknowledgment
export interface WSQueryReceived {
  type: 'query_received';
  request_id?: string;
  status: string;
}

// Union type for all WebSocket messages
export type WSMessage =
  | WSStatusUpdate
  | WSAlert
  | WSDetection
  | WSQuery
  | WSQueryResponse
  | WSQueryReceived
  | { type: 'ping' }
  | { type: 'pong' };

// Health status response
export interface HealthStatus {
  status: string;
  service: string;
  redis_connected: boolean;
  version?: string;
  uptime_seconds?: number;
}

// Feed connection test result
export interface ConnectionTestResult {
  success: boolean;
  resolution?: string;
  fps?: number;
  error?: string;
}

// Status history entry
export interface StatusHistoryEntry {
  severity: Severity;
  description: string;
  timestamp: string;
}

// Icon mapping for different status types
export const STATUS_ICONS: Record<string, string> = {
  // Green icons
  reading: '\uD83D\uDCD7',
  tv: '\uD83D\uDCFA',
  sleeping: '\uD83D\uDE34',
  eating: '\uD83C\uDF7D\uFE0F',
  calm: '\uD83E\uDDD8',
  exercise: '\uD83C\uDFC3\u200D\u2642\uFE0F',
  // Yellow icons
  unclear: '\uD83D\uDD0D',
  injury: '\uD83E\uDE79',
  distress: '\uD83D\uDE30',
  pacing: '\uD83D\uDEB6',
  // Red icons
  emergency: '\uD83D\uDEA8',
  missing: '\uD83C\uDFC3',
  danger: '\u26A0\uFE0F',
  unconscious: '\uD83D\uDEA8',
};

// Severity color mapping
export const SEVERITY_COLORS: Record<Severity, string> = {
  green: '#22c55e',
  yellow: '#eab308',
  red: '#ef4444',
};

// Severity labels
export const SEVERITY_LABELS: Record<Severity, string> = {
  green: 'Safe',
  yellow: 'Attention',
  red: 'CRITICAL',
};
