"""
Pydantic data models for Newport Demo application.

Defines shared data structures for API requests/responses and internal use.
"""
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator


class Severity(str, Enum):
    """Status severity levels."""
    GREEN = "green"
    YELLOW = "yellow"
    RED = "red"


class Detection(BaseModel):
    """Object detection result from DeepStream."""
    class_id: int = Field(..., description="Detection class ID")
    class_name: str = Field(..., description="Detection class name")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Detection confidence")
    bbox: List[float] = Field(
        ...,
        min_length=4,
        max_length=4,
        description="Bounding box [x1, y1, x2, y2]"
    )

    @field_validator("bbox")
    @classmethod
    def validate_bbox(cls, v: List[float]) -> List[float]:
        """Validate bounding box coordinates are positive."""
        if any(coord < 0 for coord in v):
            raise ValueError("Bounding box coordinates must be non-negative")
        return v


class DetectionEvent(BaseModel):
    """Detection event from DeepStream container."""
    type: str = Field(default="detection.received", description="Event type")
    stream_id: str = Field(..., description="Camera/stream identifier")
    frame_path: Optional[str] = Field(None, description="Path to saved frame")
    detections: List[Detection] = Field(
        default_factory=list,
        description="List of detections"
    )
    timestamp: float = Field(
        default_factory=lambda: datetime.utcnow().timestamp(),
        description="Event timestamp (Unix epoch)"
    )


class StreamStatus(BaseModel):
    """Current status for a monitored stream."""
    stream_id: str = Field(..., description="Camera/stream identifier")
    severity: Severity = Field(..., description="Status severity level")
    icon: str = Field(..., description="Status icon emoji")
    description: str = Field(..., description="Human-readable status description")
    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Classification confidence"
    )
    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="Status timestamp"
    )


class SummaryEvent(BaseModel):
    """VLM summary event published to Redis."""
    type: str = Field(default="summary.received", description="Event type")
    stream_id: str = Field(..., description="Camera/stream identifier")
    data: Dict[str, Any] = Field(..., description="Summary data")
    timestamp: float = Field(
        default_factory=lambda: datetime.utcnow().timestamp(),
        description="Event timestamp (Unix epoch)"
    )


class AlertLevel(str, Enum):
    """Alert urgency levels."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class Alert(BaseModel):
    """Alert generated by the system."""
    id: Optional[str] = Field(None, description="Unique alert ID")
    stream_id: str = Field(..., description="Source stream identifier")
    level: AlertLevel = Field(..., description="Alert urgency level")
    title: str = Field(..., description="Alert title")
    message: str = Field(..., description="Alert message")
    severity: Severity = Field(..., description="Associated status severity")
    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="Alert timestamp"
    )
    acknowledged: bool = Field(default=False, description="Whether alert is acknowledged")


class ProtocolRules(BaseModel):
    """User-defined monitoring protocol rules."""
    green_rules: str = Field(
        ...,
        min_length=1,
        description="Rules for GREEN (safe) status"
    )
    yellow_rules: str = Field(
        ...,
        min_length=1,
        description="Rules for YELLOW (attention) status"
    )
    red_rules: str = Field(
        ...,
        min_length=1,
        description="Rules for RED (critical) status"
    )


class StreamConfig(BaseModel):
    """Configuration for a monitored stream."""
    stream_id: str = Field(..., description="Unique stream identifier")
    name: str = Field(..., description="Human-readable stream name")
    source_uri: str = Field(..., description="RTSP or file URI for video source")
    enabled: bool = Field(default=True, description="Whether stream is active")
    protocols: Optional[ProtocolRules] = Field(
        None,
        description="Custom protocols for this stream"
    )


# WebSocket message models

class WSMessage(BaseModel):
    """Base WebSocket message."""
    type: str = Field(..., description="Message type")


class WSStatusUpdate(WSMessage):
    """WebSocket status update message."""
    type: str = Field(default="status_update")
    stream_id: str
    severity: Severity
    icon: str
    description: str
    timestamp: str


class WSAlert(WSMessage):
    """WebSocket alert message."""
    type: str = Field(default="alert_new")
    alert: Alert


class WSQuery(WSMessage):
    """WebSocket query from client."""
    type: str = Field(default="query")
    stream_id: str
    question: str
    request_id: Optional[str] = None


class WSQueryResponse(WSMessage):
    """WebSocket query response."""
    type: str = Field(default="query_response")
    request_id: Optional[str]
    answer: str
    timestamp: str


# Health check models

class HealthStatus(BaseModel):
    """Health check response."""
    status: str = Field(..., description="Overall health status")
    service: str = Field(..., description="Service name")
    redis_connected: bool = Field(..., description="Redis connection status")
    version: Optional[str] = Field(None, description="Application version")
    uptime_seconds: Optional[float] = Field(None, description="Service uptime in seconds")


class ServiceInfo(BaseModel):
    """Service information response."""
    name: str
    version: str
    docs: str = "/docs"
